
# proces name
PROCESS_NAME=inetd

# inet server config
CONFIG_FILE=/etc/inetd.conf

# inet server daemon executable file name
INETDAEMON=/usr/sbin/inetd

# additional inet server daemon argumments
INETDAEMON_ARGS=

PREAMBLE="# This file is autogenerated!"

parse_one_service()
{
	ALL_REQD_PARAMS=1

	[ ${SERVICE_NAME:-not} = "not" ]	&& ALL_REQD_PARAMS=0
	[ ${PROTOCOL:-not} = "not" ]		&& ALL_REQD_PARAMS=0
	[ ${PORT:-not} = "not" ]		&& ALL_REQD_PARAMS=0
	[ ${USER:-not} = "not" ]		&& ALL_REQD_PARAMS=0
	[ ${SERVER:-not} = "not" ]		&& ALL_REQD_PARAMS=0
	[ ${FLAGS:-not} = "not" ]		&& ALL_REQD_PARAMS=0
	[ ${DAEMON:-not} = "not" ]		&& ALL_REQD_PARAMS=0

	if [ $ALL_REQD_PARAMS -eq 0 ] ; then
		return 1
	fi

	[ "$SERVER" = "tcpd" ] && SERVER="/usr/sbin/tcpd"

	echo "$SERVICE_NAME	$SOCK_TYPE	$PROTOCOL	$FLAGS	$USER	$SERVER $DAEMON $DAEMONARGS"

	return 0
}

status_rc-inetd()
{
	return 0
}
reload_config()
{
	killproc $INETDAEMON -HUP
}
